### ISSUE TITLE
Programmatically composable queries

### ISSUE THREAD

**Issue by mfenniak** [mfenniak/rethinkdb-net#215]
I'd like rethinkdb-net to support situations like "if this checkbox is checked in the UI, add this filter to this query".  I'm not sure how you'd do that with the current LINQ expression tree approach to building queries, but it might be possible.  I'd like to investigate this, add support if necessary, and add an example or unit test that shows the usage.

**Comment by jonorossi** [comment]
I assume you mean something like the [Building ReQL queries on multiple lines section](http://rethinkdb.com/docs/cookbook/python/) for python?

**Comment by mfenniak** [comment]
Yes, that's what I had in mind.

Although, the examples of how they do that in the Python driver are actually very applicable to rethinkdb-net.  I'm not sure why I didn't think of that.  I was daydreaming about how to compose the LINQ expressions, but, it's very easy to stack the query operations.
