### ISSUE TITLE
Can realtime with winform and rethinkdb ?

### ISSUE THREAD

**Issue by lyquocnam** [mfenniak/rethinkdb-net#253]
Can realtime with winform and rethinkdb ?
this can be awesome.

**Comment by mfenniak** [comment]
Sure, you could use a Forms application and rethinkdb-net with change feed monitoring.  One of our examples has real-time change feed monitoring in a console app: https://github.com/mfenniak/rethinkdb-net/tree/master/Examples/RethinkDb.Examples.ConsoleApp.  Doing this in a forms app would be very similar, but you'd need to synchronize updates from the thread monitoring for changes to the UI thread.

**Comment by lyquocnam** [comment]
thanks so much, i try to learn with this.
