### ISSUE TITLE
Add support for other primitives to DataContractDatumConverter

### ISSUE THREAD

**Issue by mfenniak** [mfenniak/rethinkdb-net#54]
Would be nice to see the same support that data contracts have; int, uint, long, ulong, Uri, decimal, etc.  Number values might suggest supporting logging (issue #53) to warn upon data truncation?

**Comment by mattiasw2** [comment]
Testing RethinkDb and wondering about floats in DmlResponse.

I get the impression that RethinkDb can handle ints now.

Really awkward not to be able to write code like

      return res.Errors == 0;

The code is 

```
namespace RethinkDb
{
  [DataContract]
  public class DmlResponse
  {
    [DataMember(Name = "created")]
    public double Created;
    [DataMember(Name = "dropped")]
    public double Dropped;
    [DataMember(Name = "inserted")]
    public double Inserted;
    [DataMember(Name = "updated")]
    public double Updated;
    [DataMember(Name = "replaced")]
    public double Replaced;
    [DataMember(Name = "deleted")]
    public double Deleted;
    [DataMember(Name = "skipped")]
    public double Skipped;
    [DataMember(Name = "errors")]
    public double Errors;
    [DataMember(Name = "first_error")]
    public string FirstError;
    [DataMember(Name = "generated_keys")]
    public string[] GeneratedKeys;
  }
}
```

**Comment by mfenniak** [comment]
Yup, it would make sense to change those fields to a different type.  uint, perhaps?

**Comment by mfenniak** [comment]
@mattiasw2 -- PR #205 will address your concern.
